# Generated by Django 3.2.4 on 2022-03-19 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('prereqName', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('link', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('skill_name', models.CharField(max_length=100)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('timed_changes', models.DateTimeField(auto_now_add=True)),
                ('contributed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='subskill_prerequisites', to='framework.Prerequisite')),
                ('subskills', models.ManyToManyField(blank=True, related_name='subskills_under_subskill', to='framework.Skill')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('tagName', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('topic_name', models.CharField(max_length=100)),
                ('timed_changes', models.DateTimeField(auto_now_add=True)),
                ('contributed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='topic_with_this_prerequisite', to='framework.Prerequisite')),
                ('resources', models.ManyToManyField(blank=True, to='framework.Resource')),
                ('subtopics', models.ManyToManyField(blank=True, related_name='Subtopics', to='framework.Topic')),
                ('tags', models.ManyToManyField(blank=True, related_name='topic_tags', to='framework.Tag')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Superskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('superskill_name', models.CharField(max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('timed_changes', models.DateTimeField(auto_now_add=True)),
                ('Skills', models.ManyToManyField(blank=True, related_name='super_skill', to='framework.Skill')),
                ('contributed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='all_skills_with_this_prerequisite', to='framework.Prerequisite')),
                ('sub_superskills', models.ManyToManyField(blank=True, related_name='nested_Superskills', to='framework.Superskill')),
                ('tags', models.ManyToManyField(blank=True, related_name='all_skills_with_this_tag', to='framework.Tag')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTopicThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.skill')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.topic')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subskill_tags', to='framework.Tag'),
        ),
        migrations.AddField(
            model_name='skill',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='subskill_topics', through='framework.SkillTopicThroughModel', to='framework.Topic'),
        ),
    ]
