# Generated by Django 3.2.4 on 2022-01-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0001_initial'),
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subskill',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vote.vote')),
                ('subskill_name', models.CharField(max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('timed_changes', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='subskill_prerequisites', to='framework.Prerequisite')),
            ],
            bases=('vote.vote',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vote.vote')),
                ('tag_name', models.CharField(max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('topicname', models.CharField(max_length=100)),
                ('timed_changes', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='topic_with_this_prerequisite', to='framework.Prerequisite')),
                ('resources', models.ManyToManyField(blank=True, to='framework.Resource')),
                ('subtopics', models.ManyToManyField(blank=True, related_name='Subtopics', to='framework.Topic')),
                ('tags', models.ManyToManyField(blank=True, related_name='topic_tags', to='framework.Tag')),
            ],
            bases=('vote.vote',),
        ),
        migrations.CreateModel(
            name='Superskill',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vote.vote')),
                ('superskill_name', models.CharField(max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('timed_changes', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='all_skills_with_this_prerequisite', to='framework.Prerequisite')),
                ('subskills', models.ManyToManyField(blank=True, related_name='super_skill', to='framework.Subskill')),
                ('tags', models.ManyToManyField(blank=True, related_name='all_skills_with_this_tag', to='framework.Tag')),
            ],
            bases=('vote.vote',),
        ),
        migrations.AddField(
            model_name='subskill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subskill_tags', to='framework.Tag'),
        ),
        migrations.AddField(
            model_name='subskill',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='subskill_topics', to='framework.Topic'),
        ),
    ]
