# Generated by Django 3.2.5 on 2022-02-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_remove_topic_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topicname',
            new_name='topic_name',
        ),
    ]
