# Generated by Django 3.2.5 on 2022-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_auto_20220302_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subskill',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='subskill_name',
            new_name='skill_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='subskill_sub',
        ),
        migrations.RemoveField(
            model_name='superskill',
            name='subskills',
        ),
        migrations.AddField(
            model_name='skill',
            name='subskills',
            field=models.ManyToManyField(blank=True, related_name='subskills_under_subskill', to='framework.Skill'),
        ),
        migrations.AddField(
            model_name='superskill',
            name='Skills',
            field=models.ManyToManyField(blank=True, related_name='super_skill', to='framework.Skill'),
        ),
    ]
