# Generated by Django 3.2.5 on 2022-03-03 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framework', '0005_auto_20220303_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='contributed_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
