# Generated by Django 3.2.5 on 2022-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0007_auto_20220311_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
