# Generated by Django 3.2.4 on 2022-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0008_auto_20220315_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prerequisite',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superskill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
