# Generated by Django 3.2.4 on 2022-03-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0009_auto_20220316_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='superskill',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('order',)},
        ),
    ]
