# Generated by Django 3.2.4 on 2022-03-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0010_auto_20220316_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Superskill',
        ),
    ]
