# Generated by Django 3.2.4 on 2022-03-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0011_delete_superskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_changes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='contributed_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='timed_changes',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='vote_score',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
