# Generated by Django 3.2.4 on 2022-03-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0013_auto_20220319_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='skills_backlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.skill'),
        ),
    ]
